const demos = [
  {
    name: "Example 1",
    screenshotLight: "/img/screenshots/landing-1.png",
    screenshotDark: "/img/screenshots/landing-1-dark.png",
    link: "/landing-1.html",
    new: false,
  },
  {
    name: "Example 2",
    screenshotLight: "/img/screenshots/landing-2.png",
    screenshotDark: "/img/screenshots/landing-2-dark.png",
    link: "/landing-2.html",
    new: false,
  },
  {
    name: "Example 3",
    screenshotLight: "/img/screenshots/landing-3.png",
    screenshotDark: "/img/screenshots/landing-3-dark.png",
    link: "/landing-3.html",
    new: false,
  },
  {
    name: "Example 4",
    screenshotLight: "/img/screenshots/landing-4.png",
    screenshotDark: "/img/screenshots/landing-4-dark.png",
    link: "/landing-4.html",
    new: false,
  },
  {
    name: "Example 5",
    screenshotLight: "/img/screenshots/landing-5.png",
    screenshotDark: "/img/screenshots/landing-5-dark.png",
    link: "/landing-5.html",
    new: false,
  },
  {
    name: "Example 6",
    screenshotLight: "/img/screenshots/landing-6.png",
    screenshotDark: "/img/screenshots/landing-6-dark.png",
    link: "/landing-6.html",
    new: false,
  },
  {
    name: "Example 7",
    screenshotLight: "/img/screenshots/landing-7.png",
    screenshotDark: "/img/screenshots/landing-7-dark.png",
    link: "/landing-7.html",
    new: false,
  },
  {
    name: "Login",
    screenshotLight: "/img/screenshots/login.png",
    screenshotDark: "/img/screenshots/login-dark.png",
    link: "/login.html",
    new: false,
  },
  {
    name: "Signup",
    screenshotLight: "/img/screenshots/signup.png",
    screenshotDark: "/img/screenshots/signup-dark.png",
    link: "/signup.html",
    new: false,
  },
  {
    name: "Error 404",
    screenshotLight: "/img/screenshots/404.png",
    screenshotDark: "/img/screenshots/404-dark.png",
    link: "/404.html",
    new: false,
  },
  {
    name: "Elements",
    screenshotLight: "/img/screenshots/elements.png",
    screenshotDark: "/img/screenshots/elements-dark.png",
    link: "/elements.html",
    new: false,
  },
  {
    name: "Form",
    screenshotLight: "/img/screenshots/form.png",
    screenshotDark: "/img/screenshots/form-dark.png",
    link: "/form.html",
    new: false,
  },
  {
    name: "Table",
    screenshotLight: "/img/screenshots/table.png",
    screenshotDark: "/img/screenshots/table-dark.png",
    link: "/table.html",
    new: false,
  },
  {
    name: "Features",
    screenshotLight: "/img/screenshots/features.png",
    screenshotDark: "/img/screenshots/features-dark.png",
    link: "/features.html",
    new: false,
  },
  {
    name: "Content",
    screenshotLight: "/img/screenshots/content.png",
    screenshotDark: "/img/screenshots/content-dark.png",
    link: "/content.html",
    new: false,
  },
  {
    name: "Team",
    screenshotLight: "/img/screenshots/team.png",
    screenshotDark: "/img/screenshots/team-dark.png",
    link: "/team.html",
    new: false,
  },
  {
    name: "Testimonials",
    screenshotLight: "/img/screenshots/testimonials.png",
    screenshotDark: "/img/screenshots/testimonials-dark.png",
    link: "/testimonials.html",
    new: false,
  },
  {
    name: "Pricing",
    screenshotLight: "/img/screenshots/pricing.png",
    screenshotDark: "/img/screenshots/pricing-dark.png",
    link: "/pricing.html",
    new: false,
  },
  {
    name: "Call to action",
    screenshotLight: "/img/screenshots/call.png",
    screenshotDark: "/img/screenshots/call-dark.png",
    link: "/call.html",
    new: false,
  },
  {
    name: "Posts",
    screenshotLight: "/img/screenshots/posts.png",
    screenshotDark: "/img/screenshots/posts-dark.png",
    link: "/posts.html",
    new: false,
  },
  {
    name: "Video",
    screenshotLight: "/img/screenshots/video.png",
    screenshotDark: "/img/screenshots/video-dark.png",
    link: "/video.html",
    new: false,
  },
  {
    name: "Contact",
    screenshotLight: "/img/screenshots/contact.png",
    screenshotDark: "/img/screenshots/contact-dark.png",
    link: "/contact.html",
    new: false,
  },
];

export function initRenderDemos() {
  return {
    screenshots: demos,
  };
}
